# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('publish_date', models.DateTimeField(verbose_name='publish_date')),
            ],
            options={
                'verbose_name_plural': 'news',
                'verbose_name': 'news item',
            },
        ),
    ]
